# Site settings
title: Gavriella Ravid
description: An Engineer in the Works
keywords: Modern, Blogging, Fun
author: Gavriella
baseurl: "" # the subpath of your site, e.g. /blog/
url:  http://grdesigns.github.io

